### ISSUE TITLE
Unnecessary intermediate

### ISSUE THREAD

**Issue by StefanLarsson** [root42/aoc2020#1]
https://github.com/root42/aoc2020/blob/69a5f9d4f8cb244857bc0bb57e94dc316650677b/src/aoc2020/core.clj#L318-L319

These could be replaces by just `(map first)`

Also I think this
https://github.com/root42/aoc2020/blob/69a5f9d4f8cb244857bc0bb57e94dc316650677b/src/aoc2020/core.clj#L332
is probably non-idomatic and ought to be `(filter (complement insta/failure?))`

But the idea of abstracting it into a grammar is really neat! I didn't see the grammar through all the numbers and whatnot.

**Comment by root42** [comment]
Thanks, I switched away from the instaparse, so both are non-issues anymore. However I will keep in mind the complement. That was a function I didn't know about yet. And take 1 is indeed a bit stupid. :)
